# NumPy Array Basics

In [1]:
my_list = [1,2,3]

In [3]:
import numpy as np

In [4]:
arr = np.array(my_list)
print(arr)

[1 2 3]


In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(4)

array([1., 1., 1., 1.])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.linspace(0,5,10)
# start, stop, evenly spaced points
# long 1D array, not 2D

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

**Diagonal of 1**

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**arrays with random numbers**

In [15]:
np.random.rand(5)

array([0.03795492, 0.44334599, 0.47472006, 0.22030434, 0.89576673])

In [16]:
np.random.rand(5,5)

array([[0.75749111, 0.78563804, 0.7342796 , 0.24712151, 0.29258677],
       [0.32614346, 0.0664973 , 0.26357202, 0.32121985, 0.28578378],
       [0.45123549, 0.37384346, 0.06502999, 0.5164601 , 0.05935958],
       [0.71520745, 0.59828091, 0.03442779, 0.53564461, 0.51910648],
       [0.07902115, 0.47616967, 0.3295105 , 0.92914234, 0.98856978]])

**following Gaussian 정규분포**
> 기댓값이 0이고 표준편차가 1인 가우시안 표준 정규 분포를 따르는 난수를 생성한다.

In [17]:
np.random.rand(2)

array([0.42598076, 0.31184989])

In [18]:
np.random.randn(4,4)

array([[-0.75966119,  0.97004165, -0.36857734, -0.84302694],
       [ 0.06254654, -1.06338086, -0.4479469 , -0.22264073],
       [ 0.87297903,  1.24090479,  0.33348394, -0.84023241],
       [-0.01602075, -1.40236012, -0.03367312, -0.42753812]])

**random integer**  
*시작(포함), 끝(포함x), 개수*

In [19]:
np.random.randint(1,100,10)

array([48, 58, 50, 26,  9, 90, 74, 10, 33, 68])

In [20]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

**Total size must be identical**

In [23]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
ranarr.max()

46

In [26]:
ranarr.min()

0

**Get the index of max value**

In [27]:
ranarr.argmax()

5

In [28]:
ranarr.argmin()

0

In [30]:
arr.shape

(25,)

In [31]:
arr = arr.reshape(5,5)
arr.shape

(5, 5)

**Get data type**

In [32]:
arr.dtype

dtype('int32')

**임포트할 때 이렇게 할 수도 있다!**

In [34]:
from numpy.random import randint
randint(2,10)

2

# NumPy Indexing and Selection

In [36]:
arr = np.arange(0,11)

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr[8]

8

In [39]:
arr[1:5]

array([1, 2, 3, 4])

In [40]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [41]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

**Broadcasting**

In [42]:
arr[0:5] = 100

In [43]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

**And broadcasting changes the *original array***
> numpy is just referencing the original one. Just viewing the original ones

In [49]:
slice_of = arr[:6]

In [50]:
slice_of

array([100, 100, 100, 100, 100,   5])

In [51]:
slice_of[:] = 99

In [52]:
slice_of

array([99, 99, 99, 99, 99, 99])

In [53]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

**Copy of an Array**

In [54]:
arr_copy = arr.copy()

In [55]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [57]:
arr_copy[:] = 100

In [58]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [59]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

**2D array**

In [60]:
arr_1d = np.arange(5,50,5)

In [65]:
arr_2d = arr_1d.reshape(3,3)
print(arr_2d)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


**Double Bracket Notation [Row][Column]**

In [64]:
arr_2d[0][0]

5

In [66]:
arr_2d[0]

array([ 5, 10, 15])

In [67]:
arr_2d[1,2]

30

**2행까지 슬라이스, 1열부터 슬라이스**

In [68]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [70]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [71]:
arr_2d[1:]

array([[20, 25, 30],
       [35, 40, 45]])

In [73]:
arr_2d[1:,:]

array([[20, 25, 30],
       [35, 40, 45]])

**Comparison**
> Conditional Selection

In [75]:
arr = np.arange(1,11)

In [76]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
bool_arr = arr > 5
print(bool_arr)

[False False False False False  True  True  True  True  True]


In [80]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [81]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [85]:
arr[arr<3]

array([1, 2])

# Numpy Operations
- Array with Array
- Array with Scalars
- Universal Array Functions

In [86]:
arr = np.arange(0,11)

In [87]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**배열과 배열 연산**

In [88]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [89]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [90]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

**배열과 스칼라 연산**  
*합/곱/차/나누기 다 된다.*

In [91]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [92]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

**Numpy는 에러보다 경고를 띄운다.**

In [93]:
arr / arr

C:\Users\USER\Anaconda3\envs\ML\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [94]:
1 / arr

C:\Users\USER\Anaconda3\envs\ML\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

*제곱, 루트, 지수, 로그 연산도 쌉가능*

In [96]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [97]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [98]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [99]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [100]:
np.log(arr)

C:\Users\USER\Anaconda3\envs\ML\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])